---

- name: Converge
  hosts: all
  gather_facts: true

  roles:
    - role: iamenr0s.ansible_role_cgroup
      vars:
        cgroup_enforce_mode: "v2"
        cgroup_extra_kernel_params:
          - audit=1

  post_tasks:
    - name: Read /etc/default/grub
      ansible.builtin.slurp:
        path: /etc/default/grub
      register: grub_file

    - name: Assert v2 kernel params present
      ansible.builtin.assert:
        that:
          - (grub_file.content | b64decode) is search('systemd.unified_cgroup_hierarchy=1')
          - (grub_file.content | b64decode) is search('audit=1')
